"""add motions tables and party motion_summary

Revision ID: 1b1b0e125970
Revises: 51c40c36a574
Create Date: 2026-02-16 21:45:14.287179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b1b0e125970'
down_revision: Union[str, Sequence[str], None] = '51c40c36a574'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('motions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('election_id', sa.Integer(), nullable=False),
    sa.Column('notubiz_item_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('motion_type', sa.String(length=50), nullable=True),
    sa.Column('result', sa.String(length=50), nullable=True),
    sa.Column('submission_date', sa.Date(), nullable=True),
    sa.Column('resolution_date', sa.Date(), nullable=True),
    sa.Column('toelichting', sa.Text(), nullable=True),
    sa.Column('document_url', sa.String(length=500), nullable=True),
    sa.Column('resolution_document_url', sa.String(length=500), nullable=True),
    sa.Column('meeting_event_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['election_id'], ['elections.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('notubiz_item_id')
    )
    op.create_table('motion_parties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('motion_id', sa.Integer(), nullable=False),
    sa.Column('party_id', sa.Integer(), nullable=True),
    sa.Column('notubiz_party_name', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['motion_id'], ['motions.id'], ),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('motion_candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('motion_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=True),
    sa.Column('notubiz_person_name', sa.String(length=200), nullable=False),
    sa.Column('notubiz_person_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['motion_id'], ['motions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('parties', sa.Column('motion_summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parties', 'motion_summary')
    op.drop_table('motion_candidates')
    op.drop_table('motion_parties')
    op.drop_table('motions')
    # ### end Alembic commands ###
